name: Deploy

# Manual trigger for this workflow
on: workflow_dispatch

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
  REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
  REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
  REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
  REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
  REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
  REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}

permissions:
  id-token: write
  contents: write
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy to Github Pages
    # Runs on mac os
    runs-on: macos-latest
    steps:
      # Checks out a repo so the workflow can access it
      - uses: actions/checkout@v3
      # Setup the node with version 16.13.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
      # Build the debug test app while increasing the node space and Yarn's network timeout to prevent timeour when downloading packages
      - name: Install packages and deploy
        env:
          CI: ""
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
      
